### ISSUE TITLE
Error with npm install npm ERR! Invalid version: "1.0"

### ISSUE THREAD

**Issue by gmlunesa** [covid19naga/covid19naga-site#1]
Zeit Now deployment error.
```
23:09:11.249  Running "npm run build"
23:09:11.424  npm ERR! Invalid version: "1.0"
23:09:11.427  npm ERR! A complete log of this run can be found in:
23:09:11.427  npm ERR!     /zeit/.npm/_logs/2020-04-08T15_09_11_424Z-debug.log
23:09:11.436  Error: Exited with 1
23:09:11.436      at ChildProcess.<anonymous> (/zeit/f73854a5c95ea7a1/.build-utils/node_modules/@now/build-utils/dist/index.js:31349:24)
23:09:11.436      at ChildProcess.emit (events.js:223:5)
23:09:11.436      at ChildProcess.EventEmitter.emit (domain.js:475:20)
23:09:11.436      at maybeClose (internal/child_process.js:1021:16)
23:09:11.436      at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
23:09:13.062  Done with "package.json"
```

**Comment by gmlunesa** [comment]
Related issue: https://github.com/npm/npm/issues/7445

**Comment by gmlunesa** [comment]
Fix at: https://github.com/covid19naga/covid19naga-site/commit/2a039d2d9d1c140e61d61c75d6521636d2ad71cb
